server:
  port: 18089

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/h2/db
    password: h2
    username: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS:127.0.0.1:9092,127.0.0.1:10092,127.0.0.1:11092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-
      acks: -1
      retries: 3