server:
  port: 18088

spring:
  application:
    name: pay-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/h2/pay
    password: h2
    username: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS:127.0.0.1:9092,127.0.0.1:10092,127.0.0.1:11092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-
      acks: -1
      retries: 3
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      isolation-level: read_committed
      properties:
        spring.json.trusted.packages: "*"